FROM win-macosx-pookie-lvl1-base:latest

RUN apt-get update && apt-get install -y \
    docker.io \
    python3-requests \
    python3-bs4 \
    && rm -rf /var/lib/apt/lists/*

COPY src/pookie.py .
COPY src/python_version_fetcher.py .
COPY src/docker_images_builder.py .
COPY src/docker_images_runner.py .

COPY images /images

ENTRYPOINT ["python3", "/pookie.py"]