# This file is part of pookie.

# Copyright (C) 2025 Andrés Lillo Ortiz

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

FROM win-macosx-pookie-lvl1-base:latest

RUN apt-get update && apt-get install -y \
    xz-utils \
    clang \
    llvm-dev \
    libxml2-dev \
    uuid-dev \
    bzip2 \
    libssl-dev \
    libbz2-dev \
    zlib1g-dev \
    cmake \
    patch \
    liblzma-dev \
    build-essential \
    patch \
    cpio \
    zip \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Download and install osxcross
RUN wget https://github.com/joseluisq/macosx-sdks/releases/download/11.1/MacOSX11.1.sdk.tar.xz && \
    git clone https://github.com/tpoechtrager/osxcross.git && \
    mv MacOSX11.1.sdk.tar.xz osxcross/tarballs/ && \
    cd osxcross && tools/get_dependencies.sh && \
    echo | ./build.sh

ENV PATH="/osxcross/target/bin:${PATH}"