FROM win-macosx-pookie-lvl2-osxcross:latest

ARG PYTHON_URL

# Download and install Python for cross-compilation
RUN PYTHON_URL_TEMP=${PYTHON_URL} && \
    PYTHON_VERSION=$(echo "$PYTHON_URL_TEMP" | grep -oP 'cpython-\K[0-9]+\.[0-9]+\.[0-9]+') && \
    wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz && \
    tar -xJf Python-${PYTHON_VERSION}.tar.xz && \
    cd Python-${PYTHON_VERSION} && \
    ./configure && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -rf Python-${PYTHON_VERSION}*

# Download and install Python
RUN wget -O python.tar.gz ${PYTHON_URL} && \
    tar -xvzf python.tar.gz && \
    rm -f python.tar.gz