# This file is part of pookie.

# Copyright (C) 2025 Andrés Lillo Ortiz

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

FROM win-macosx-pookie-lvl2-msvc-mingw64:latest

ARG PYTHON_URL

# Download and install Python
RUN wget -O python.tar.gz ${PYTHON_URL} && \
    tar -xvzf python.tar.gz && \
    rm -f python.tar.gz

# Fix the sysconfigdata file
RUN cd /python/lib/python* && \
    sed -i 's#/install#/python#g' _sysconfigdata__*.py && \
    find . -name '__pycache__' -type d -exec rm -rf {} +