# This file is part of pookie.

# Copyright (C) 2025 Andrés Lillo Ortiz

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

FROM win-macosx-pookie-lvl1-base:latest

RUN dpkg --add-architecture i386
RUN apt-get update && apt-get install -y \
    msitools \
    wine64 \
    wine32:i386 \
    winetricks \
    ca-certificates \
    winbind \
    cabextract \
    && rm -rf /var/lib/apt/lists/*

# Download and install mingw-w64
RUN wget https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-12.0.0-ucrt-r3/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip && \
    unzip winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip && \
    rm winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip

# Download and install MSVC
RUN git clone https://github.com/mstorsjo/msvc-wine.git && \
    cd msvc-wine && \
    echo "yes" | ./vsdownload.py --dest ../my_msvc/opt/msvc && \
    ./install.sh ../my_msvc/opt/msvc && \
    cd .. && rm -r msvc-wine

# Download and install wine
RUN mkdir -pm755 /etc/apt/keyrings && \
    wget -O - https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key - && \
    wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources && \
    apt-get update && \
    apt install -y --install-recommends winehq-stable