# This file is part of pookie.

# Copyright (C) 2025 Andrés Lillo Ortiz

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

FROM win-macosx-pookie-lvl2-msvc-mingw64:latest

ARG PYTHON_URL

# # Set the Python and pip executables
# ARG PYTHON_EXECUTABLE="wine /python/python.exe"
# ARG PIP_EXECUTABLE="wine /python/python.exe -m pip"

# Set the Python and pip executables
ARG PYTHON_EXECUTABLE="/python_cross/bin/python3"
ARG PIP_EXECUTABLE="/python_cross/bin/pip3"

# Download and install Python for cross-compilation
RUN bash -c '\
    LINUX_URL="${PYTHON_URL/pc-windows-msvc/unknown-linux-gnu}" && \
    wget -O python_cross.tar.gz "$LINUX_URL" && \
    tar -xvzf python_cross.tar.gz && \
    mv python python_cross && \
    rm -f python_cross.tar.gz \
    '

# Fix the sysconfigdata file for cross-compilation
RUN cd /python_cross/lib/python* && \
    sed -i 's#/install#/python_cross#g' _sysconfigdata__*.py && \
    find . -name '__pycache__' -type d -exec rm -rf {} +

# Download and install Python
RUN wget -O python.tar.gz ${PYTHON_URL} && \
    tar -xvzf python.tar.gz && \
    rm -f python.tar.gz

RUN bash -c "\
    minor_version=\$(echo \"\$PYTHON_URL\" | sed -n 's/.*cpython-[0-9]*\\.\\([0-9]*\\)\\..*/\\1/p') && \
    echo -e \"\nbuild_time_vars[\\\"EXT_SUFFIX\\\"] = \\\".cp-3\${minor_version}-win_amd64.pyd\\\"\" >> /python_cross/lib/python*/_sysconfigdata* && \
    echo -e \"\nbuild_time_vars[\\\"SOABI\\\"] = \\\"cp-3\${minor_version}-win_amd64\\\"\" >> /python_cross/lib/python*/_sysconfigdata* && \
    echo -e \"\nbuild_time_vars[\\\"SHLIB_SUFFIX\\\"] = \\\".pyd\\\"\" >> /python_cross/lib/python*/_sysconfigdata*"

# Generate the static library libpython310.a from python310.dll for MinGW linking
RUN bash -c "\
    minor_version=\$(echo \"\$PYTHON_URL\" | sed -n 's/.*cpython-[0-9]*\\.\\([0-9]*\\)\\..*/\\1/p') && \
    cd /python/libs && \
    gendef /python/python3\${minor_version}.dll && \
    x86_64-w64-mingw32-dlltool -d python3\${minor_version}.def -l libpython3\${minor_version}.a -D python3\${minor_version}.dll"

# Create wrapper scripts for Python and pip
RUN mkdir -p /wrapper && \
    printf "#!/bin/bash\n${PYTHON_EXECUTABLE} \"\$@\"" > /wrapper/python3 && \
    printf "#!/bin/bash\n${PYTHON_EXECUTABLE} \"\$@\"" > /wrapper/python && \
    printf "#!/bin/bash\n${PIP_EXECUTABLE} \"\$@\"" > /wrapper/pip3 && \
    printf "#!/bin/bash\n${PIP_EXECUTABLE} \"\$@\"" > /wrapper/pip && \
    chmod +x /wrapper/python3 /wrapper/python /wrapper/pip3 /wrapper/pip

# Set the PATH to include the wrapper directory
ENV PATH="/wrapper:${PATH}"