FROM win-macosx-pookie-lvl1-base:latest

RUN dpkg --add-architecture i386
RUN apt-get update && apt-get install -y \
    msitools \
    wine64 \
    wine32:i386 \
    winetricks \
    ca-certificates \
    winbind \
    unzip \
    cabextract \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-12.0.0-ucrt-r3/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip && \
    unzip winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip && \
    rm winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip

RUN git clone https://github.com/mstorsjo/msvc-wine.git && \
    cd msvc-wine && \
    echo "yes" | ./vsdownload.py --dest ../my_msvc/opt/msvc && \
    ./install.sh ../my_msvc/opt/msvc && \
    cd .. && rm -r msvc-wine