FROM win-macosx-pookie-lvl1-base:latest

RUN apt-get update && apt-get install -y \
    cpio \
    xz-utils \
    clang \
    llvm-dev \
    libxml2-dev \
    uuid-dev \
    bzip2 \
    libssl-dev \
    libbz2-dev \
    zlib1g-dev \
    cmake \
    patch \
    liblzma-dev \
    build-essential \
    patch \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/joseluisq/macosx-sdks/releases/download/11.1/MacOSX11.1.sdk.tar.xz && \
    git clone https://github.com/tpoechtrager/osxcross.git && \
    mv MacOSX11.1.sdk.tar.xz osxcross/tarballs/ && \
    cd osxcross && tools/get_dependencies.sh && \
    echo | ./build.sh

ENV PATH="/osxcross/target/bin:${PATH}"