FROM win-macosx-pookie-lvl1-base:latest

RUN dpkg --add-architecture i386
RUN apt-get update && apt-get install -y \
    msitools \
    wine64 \
    wine32:i386 \
    winetricks \
    ca-certificates \
    winbind \
    cabextract \
    && rm -rf /var/lib/apt/lists/*

# Download and install mingw-w64
RUN wget https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-12.0.0-ucrt-r3/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip && \
    unzip winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip && \
    rm winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.zip

# Download and install MSVC
RUN git clone https://github.com/mstorsjo/msvc-wine.git && \
    cd msvc-wine && \
    echo "yes" | ./vsdownload.py --dest ../my_msvc/opt/msvc && \
    ./install.sh ../my_msvc/opt/msvc && \
    cd .. && rm -r msvc-wine

# Download and install wine
RUN mkdir -pm755 /etc/apt/keyrings && \
    wget -O - https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key - && \
    wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources && \
    apt-get update && \
    apt install -y --install-recommends winehq-stable