# This file is part of pookie.

# Copyright (C) 2025 Andrés Lillo Ortiz

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

FROM musllinux-lvl1-base:latest

# Download and install the musl cross compiler for aarch64
RUN wget https://more.musl.cc/10.2.1/x86_64-linux-musl/aarch64-linux-musl-cross.tgz && \
    tar -xvzf aarch64-linux-musl-cross.tgz && \
    rm -f aarch64-linux-musl-cross.tgz

# Add the cross compiler to the PATH
ENV PATH="/aarch64-linux-musl-cross/bin:${PATH}"

# Install qemu
RUN apk add --no-cache \
    qemu-aarch64