FROM manylinux-lvl2-gnu-gcc:latest

ARG PYTHON_URL
ARG PYTHON_VERSION

# Instalar Python
RUN wget ${PYTHON_URL} && \
    tar -xJf Python-${PYTHON_VERSION}.tar.xz && \
    cd Python-${PYTHON_VERSION} && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -rf Python-${PYTHON_VERSION}*
