# This file is part of pookie.

# Copyright (C) 2025 Andrés Lillo Ortiz

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

FROM manylinux-lvl1-base:latest

RUN apt-get update && apt-get install -y \
    gcc-s390x-linux-gnu \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/s390x-linux-gnu/lib/ld64.so.1 /lib/ld64.so.1