# This file is part of pookie.

# Copyright (C) 2025 Andrés Lillo Ortiz

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

FROM manylinux-lvl2-gnu-gcc:latest

ARG PYTHON_URL

# Set the Python and pip executables
ARG PYTHON_EXECUTABLE="/python/bin/python3"
ARG PIP_EXECUTABLE="/python/bin/pip3"

# Download and install Python
RUN wget -O python.tar.gz ${PYTHON_URL} && \
    tar -xvzf python.tar.gz && \
    rm -f python.tar.gz

# Fix the sysconfigdata file
RUN cd /python/lib/python* && \
    sed -i 's#/install#/python#g' _sysconfigdata__*.py && \
    find . -name '__pycache__' -type d -exec rm -rf {} +

# Create wrapper scripts for Python and pip
RUN mkdir -p /wrapper && \
    printf "#!/bin/bash\n${PYTHON_EXECUTABLE} \"\$@\"" > /wrapper/python3 && \
    printf "#!/bin/bash\n${PYTHON_EXECUTABLE} \"\$@\"" > /wrapper/python && \
    printf "#!/bin/bash\n${PIP_EXECUTABLE} \"\$@\"" > /wrapper/pip3 && \
    printf "#!/bin/bash\n${PIP_EXECUTABLE} \"\$@\"" > /wrapper/pip && \
    chmod +x /wrapper/python3 /wrapper/python /wrapper/pip3 /wrapper/pip

# Set the PATH to include the wrapper directory
ENV PATH="/wrapper:${PATH}"